# Site
repository: sproogen/resume-theme
favicon: images/green.jpg

# Content configuration version
version: 2

# Personal info
name: Nico Schiavone
title: Student 
email: nschiavo@ualberta.ca
website: mesophil.github.io

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username:
github_username:  mesophil
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: nicoschiavone
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/defect.png
about_content: | # this will include new lines to allow paragraphs
  Hello! My name is Nico Schiavone. I'm a current fifth year Engineering Physics Major, Mathematics Minor at the University of Alberta. I work as a computer vision researcher with Dr. Xingyu Li.
  
  After graduation, I plan to enter into a Ph.D in Computer Science!

  My strengths are <mark>Python</mark> and <mark>Algorithm Design</mark>. I also know <mark>Java</mark>, <mark>C++</mark>, and a bit of <mark>C</mark>.

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Publications and Presentations
    layout: text
    content: |
      - **N. Schiavone**, X. Li (2023). *Generative Models for Data Efficient Classification*. [Poster, uAlberta Dean’s Research Award Presentations ‘23]
      - **N. Schiavone**, J. Wang, S. Li, R. Zemp, X. Li (2023). **MyriadAL: Active Few Shot Learning for Histopathology**. [Preprint available on arXiv, currently *under review*].
      - **N. Schiavone**, F. Marsiglio (2021). *Algorithmic Matrix Mechanics for Superconductors*. [Poster, uAlberta Undergraduate Physics Symposium ‘21].
      - **N. Schiavone**, E. Davidge, N. Ray, A. Hess, R. Kube (2018). *On the Role of Neural Networks and Deep Learning in the Identification of Breast Cancer Cells*. [Poster, uAlberta Computing Science Symposium ‘18]

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: TELUS
        link: telus.com
        link_text: Python | C++ | GCP | Postgres | Flask | PyTorch
        # additional_links:
        #   - title: Python | C++ | GCP | Postgres | Flask | PyTorch
        sub_title: Software Engineer Co-Op
        caption: January 2023 - Present
        # quote: >
        #   Python | C++ | GCP | Postgres | Flask | PyTorch
        description: | # this will include new lines to allow paragraphs
            Making quality software is a difficult, time consuming process. At TELUS, I designed systems from the ground up, leading to significant time-saves across multiple teams. I spearheaded the development of an XML analysis tool for 20+ person teams, automatically correcting errors between sets of files, and reducing the time spent per file by up to 95%. 
            
            I also developed a document extraction tool for the standards team in Python, using semi-supervised learning and OCR tech, potentially increasing the efficiency of data transfer by 90%. Finally, I finished the development and oversaw the prototyping process for a revenue prediction tool used for planning cell towers, opening a new avenue for the planning and strategy team.

      - layout: left
        title: University of Alberta
        link: ualberta.ca
        link_text: Python | PyTorch
        # additional_links:
        #   - title: Python | PyTorch
        sub_title: Machine Learning Researcher
        caption: January 2023 - Present
        # quote: >
        #   Python | PyTorch
        description: | # this will include new lines to allow paragraphs
            As a machine learning researcher under Dr. Xingyu Li, I tackled the problem of how to use the world's rapidly growing repository of unlabelled data. I designed a novel algorithm for active few shot learning in computer vision that competed with state-of-the-art algorithms while using 80% less annotation data. 
            
            I wrote a co-first author paper based on this work, which is currently under review in a prestigious computer vision conference.

      - layout: left
        title: TRIUMF
        link: triumf.ca
        link_text: C++ | Python
        # additional_links:
        #   - title: Python | PyTorch
        sub_title: Research & Development Co-Op
        caption: May 2022 - August 2022
        # quote: >
        #   Python | PyTorch
        description: | # this will include new lines to allow paragraphs
            At TRIUMF, Canada's particle accelerator, I worked on the international collaboration project Hyper-Kamiokande. I took up the lead role in operating and maintaining a DAQ gantry and laser setup. I documented the C++ programs that allowed the gantry to move in precise increments, and I used Python scripts to calibrate each individual component for optimal accuracy.

            During my tenure at the lab, I also noticed that the test facility lacked a proper security system, so I designed a Raspberry-Pi based safety system to allow for a more streamlined workflow in the future.

      - layout: left
        title: Marsiglio Group @ UofA
        link: https://apps.ualberta.ca/directory/person/fm3
        link_text: Julia | Python
        # additional_links:
        #   - title: Python | PyTorch
        sub_title: Quantum Physics Researcher
        caption: May 2021 - August 2021
        # quote: >
        #   Python | PyTorch
        description: | # this will include new lines to allow paragraphs
            As part of the Marsiglio Research Group at the University of Alberta, I researched the effect of inhomogeneous pairing interactions on the symmetry of the superconducting state. In the process, I implemented a work based on Bardeen-Cooper-Schrieffer theory and Bogliubov-de Gennes formalism in Python, and later Julia. I performed a time complexity analysis and optimized the calculation algorithms, leading to 75% faster runtimes. 

      - layout: left
        title: Tang Group @ UofA
        link: https://sites.ualberta.ca/~ttang1/
        link_text: C++ | Python
        # additional_links:
        #   - title: Python | PyTorch
        sub_title: Mechanical Engineering Researcher
        caption: May 2020 - August 2020
        # quote: >
        #   Python | PyTorch
        description: | # this will include new lines to allow paragraphs
            The recyclability of Lithium Ion batteries is a longstanding issue in sustainable tech. I simulated and tested a new design for easily recyclable lithium ion batteries, which used a nonstandard material cover to minimize the surface interactions. I generated the data in ABAQUS, and analyzed it in C++/Python.

      - layout: left
        title: Robotics & Vision Lab @ UofA
        link: mesophil.github.io
        link_text: Python | TensorFlow | C
        sub_title: Software Engineer / Machine Learning Research Intern
        caption: July 2018 - Aug 2018
        description: | # this will include new lines to allow paragraphs
            One of my earliest forays into machine learning. I won a scholarship to take part in cutting edge computer vision research with Dr. Nilanjan Ray. Together, we obtained and built a custom dataset for breast cancer, and trained a CNN to classify these images with 90+% accuracy in a supervised setting.

            Simultaneously, I worked with my peers in developing a line-tracking robot with collision avoidance, which successfully navigated a difficult course without errors.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Alberta
        caption: 2019 - 2024
        sub_title: B.Sc Electrical and Computer Engineering - Engineering Physics, Mathematics Minor
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          At the University of Alberta, I learned that despite the surprising breadth of STEM fields, they are all much more closely connected than they let on. I took some of the most advanced mathematics, physics, electrical engineering, systems, and computing classes offered. I also got involved in research at every opportunity, even researching alongside my most recent developer position. I also got involved in competitive programming, and made it to Cyan in CodeForces.

          I am the President and founder of Gears in the Dark, a 40+ person tabletop gaming club. I was also a co-founder of Healthverse, a medical supplies redistribution charity that operated from 2019-2022. In addition, I was the merchandise coordinator for the Engineering Physics club from 2021-2022 (to record sales).

          My cumulative GPA to date is 4.0/4.0, and I have held first class standing from 2019-2023.

  - title: Awards
    layout: text
    content: |
      - NSERC Undergraduate Student Research Award (2022 [declined], 2021, 2020)
      - Joseph and Edwina Charyk Scholarship in Engineering Physics (2022, 2021)
      - Louise McKinney Scholarship (2022)
      - Undergraduate Student Scholarship (2022, 2021)
      - Undergraduate Leadership Award (2022)
      - Jason Lang Scholarship (2021, 2020)
      - University of Alberta Inspiring Leadership Award (2020)
      - AP National Scholar (12 exams, 2019)
      - HIP Computing Science Scholar (2018)

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Occasionally, I take a break from programming or research. At those times, I can be found indulging in one of my hobbies:
      - Figure Drawing
      - Cooking (esp. baking)
      - Building mechanical keyboards
      - Tabletop gaming
      - Playing ARPGs

# Footer
footer_show_references: true
references_title: Made with love and thievery

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
